# Generated by Django 5.2.8 on 2026-02-20 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_userorder_options_alter_tags_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='event_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
